services:
  db:
    image: postgres:15
    container_name: postgres-server
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi123
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: unless-stopped

  redis1:
    image: redis:8.0.2
    container_name: redis1
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "locaTracer123"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "locaTracer123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    # restart: unless-stopped

  redis2:
    image: redis:8.0.2
    container_name: redis2
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "locaTracer123"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "-a", "locaTracer123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    # restart: unless-stopped

  alembic:
    build:
      context: .
      dockerfile: alembic/Dockerfile
    container_name: alembic
    working_dir: /app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://fastapi_user:fastapi123@db:5432/app_db
    depends_on:
      - db
    command: ["upgrade", "head"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: location_tracker_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://fastapi_user:fastapi123@db/app_db
      REDIS_URLS: redis://:locaTracer123@redis1:6379/0,redis://:locaTracer123@redis2:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis1
      - redis2
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
volumes:
  postgres_data:
