CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "full_name" varchar,
  "username" varchar(255) UNIQUE,
  "email" varchar UNIQUE,
  "phone_number" varchar,
  "hashed_password" varchar(255),
  "is_active" boolean,
  "role" varchar,
  "last_login" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(1024),
  "hashed_key" varchar(255),
  "capacity" int,
  "member_count" int,
  "owner_id" int NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "memberships" (
  "user_id" int NOT NULL,
  "group_id" int NOT NULL,
  "joined_at" timestamp
);

CREATE INDEX ON "users" ("full_name");

CREATE INDEX ON "users" ("phone_number");

CREATE INDEX ON "groups" ("owner_id");

CREATE INDEX ON "memberships" ("user_id");

CREATE INDEX ON "memberships" ("group_id");

ALTER TABLE "groups" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "memberships" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id");
