name: Test and Lint

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry virtualenv
        run: poetry config virtualenvs.in-project true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install test dependencies
        run: make install-test

      - name: Run unit tests
        run: make unit-test

  lint:
    name: Run Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry virtualenv
        run: poetry config virtualenvs.in-project true

      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cache/pypoetry
      #       .venv
      #     key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-poetry-

      - name: Install check dependencies
        run: make install-check

      - name: Run lint check
        run: make check
